### PR TITLE
PEP8 Compliance and several fixes

### PR DESCRIPTION
**Pull request by clementpoiret**
Hi,

I propose several changes to improve `neurospin_to_bids.py` which is causing some issues:
* Several fixes for PEP8 compliance, which - I hope - should improve readability and facilitate subsequent maintenance,
* fixed `readme_input` being assigned but never used. Whatever the user inputs, it wasn't written into the `readme` file.

### CODE REVIEW

**Comment by clementpoiret** [comment]
[‘a’, ‘b’, ‘c’] in examples are incorrect and lead to a wrongly formatted *.json file. Therefore, I update the input prompts to help new users.
The input `['a', 'b', 'c']` is incorrect and should be `a, b, c` for correct parsing

**Comment by clementpoiret** [comment]
`acq_label` wasn't taken into consideration because left unassigned. Fixed in `8b3433f`
`dwi` wasn't supported in the loop. Fixed in `cbeae5e`

**Comment by isadenghien** [comment]
Thanks Clément for those improvements. I ran a small test on my workstation, it's ok for me. I suppose the bids script now requires a specific repository. I'm going to check with the others involved.

**Comment by clementpoiret** [comment]
No problem :) 
Yes I agree with you, I think it could be a good idea to have a specific repository for neurospin_to_bids

Have a nice day,
Clément

**Pull request merged**
